# Decap CMS + Next.js + Vercel (backend: GitHub)
backend:
  name: github
  repo: faverl/blog-rf      # owner/repo (no URL)
  branch: main
  base_url: "https://blog-rf.vercel.app"  # cambia si tu dominio es otro
  auth_endpoint: "/api/decap/auth"        # endpoint OAuth en este proyecto

publish_mode: editorial_workflow
locale: es
logo_url: /favicon.svg

# Ubicación de medios (requerido)
media_folder: public/uploads     # se guarda en el repo
public_folder: /uploads          # se sirve en el sitio

# Importante: no declares media_library: "default"
# (la librería integrada ya viene incluida; declarar "default" provoca error)

collections:
  - name: blog
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    editor: { preview: true }
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Autor", name: "author", widget: "string" }
      - { label: "Imagen destacada", name: "featuredImage", widget: "image", required: false }
      - { label: "Resumen", name: "excerpt", widget: "text", required: false }
      - { label: "Borrador", name: "draft", widget: "boolean", default: false, required: false }
      - { label: "Contenido", name: "body", widget: "markdown" }

  - name: news
    label: "Noticias"
    folder: "content/news"
    create: true
    slug: "{{slug}}"
    editor: { preview: true }
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Autor", name: "author", widget: "string" }
      - { label: "Imagen destacada", name: "featuredImage", widget: "image", required: false }
      - { label: "Resumen", name: "excerpt", widget: "text", required: false }
      - { label: "Borrador", name: "draft", widget: "boolean", default: false, required: false }
      - { label: "Contenido", name: "body", widget: "markdown" }
