# Configuración Decap CMS para Next.js sirviendo /admin desde /public
# IMPORTANTE: repo usa el formato "owner/repo", no una URL.
backend:
  name: github
  repo: faverl/blog-rf         # <-- CORREGIDO
  branch: main
  # Si usas el flujo OAuth propio (recomendado):
  # base_url: "https://TU-DOMINIO"   # CAMBIA por tu dominio en Vercel
  # auth_endpoint: "/api/decap/auth"

publish_mode: editorial_workflow
locale: es
logo_url: /favicon.svg

# Requeridos para medios
media_folder: public/uploads
public_folder: /uploads

# Añadimos media_library para satisfacer validadores y usar la lib por defecto
media_library:
  name: "default"

# Colecciones de contenido
collections:
  - name: blog
    label: "Blog"
    label_singular: "Entrada de Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    editor: { preview: true }
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Autor", name: "author", widget: "string" }
      - { label: "Imagen destacada", name: "featuredImage", widget: "image", required: false }
      - { label: "Resumen", name: "excerpt", widget: "text", required: false }
      - { label: "Borrador", name: "draft", widget: "boolean", default: false, required: false }
      - { label: "Contenido", name: "body", widget: "markdown" }

  - name: news
    label: "Noticias"
    label_singular: "Noticia"
    folder: "content/news"
    create: true
    slug: "{{slug}}"
    editor: { preview: true }
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Autor", name: "author", widget: "string" }
      - { label: "Imagen destacada", name: "featuredImage", widget: "image", required: false }
      - { label: "Resumen", name: "excerpt", widget: "text", required: false }
      - { label: "Borrador", name: "draft", widget: "boolean", default: false, required: false }
      - { label: "Contenido", name: "body", widget: "markdown" }
